# Generated by Django 4.1 on 2023-11-02 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_create_date_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 18, 11, 19, 714909, tzinfo=datetime.timezone.utc)),
        ),
    ]
