# Generated by Django 4.1 on 2023-11-02 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 18, 17, 55, 134147, tzinfo=datetime.timezone.utc)),
        ),
    ]
