# Generated by Django 4.1 on 2023-11-02 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_comment_create_date_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 18, 20, 49, 529362, tzinfo=datetime.timezone.utc)),
        ),
    ]
