# Generated by Django 4.1 on 2023-11-02 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_created_date_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 18, 24, 15, 766332, tzinfo=datetime.timezone.utc)),
        ),
    ]
